# Generated by Django 5.2.17 on 2026-09-14 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кличка')),
                ('breed', models.CharField(max_length=100, verbose_name='Порода')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='ЧПУ-ссылка')),
                ('bio', models.TextField(verbose_name='Особенности  ухода, рацион, противопоказания')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичный доступ')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Питомец',
                'verbose_name_plural': 'Питомцы',
                'ordering': ['name'],
            },
        ),
    ]
